from django.conf import settings
from constants import DEFAULT_ZIPKIN_DATA_STORE_CLASS, DEFAULT_ZIPKIN_LOGGER_NAME, \
    DEFAULT_ZIPKIN_SERVICE_NAME, DEFAULT_ZIPKIN_ID_GENERATOR_CLASS

ZIPKIN_SERVICE_NAME = getattr(settings, 'ZIPKIN_SERVICE_NAME', DEFAULT_ZIPKIN_SERVICE_NAME)
ZIPKIN_LOGGER_NAME = getattr(settings, 'ZIPKIN_LOGGER_NAME', DEFAULT_ZIPKIN_LOGGER_NAME)
ZIPKIN_DATA_STORE_CLASS = getattr(settings, 'ZIPKIN_DATA_STORE_CLASS', DEFAULT_ZIPKIN_DATA_STORE_CLASS)
ZIPKIN_ID_GENERATOR_CLASS = getattr(settings, 'ZIPKIN_ID_GENERATOR_CLASS', DEFAULT_ZIPKIN_ID_GENERATOR_CLASS)
